#!/bin/sh

# PROVIDE: quark
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="quark"
rcvar="quark_enable"
desc="Quark Reverse Proxy"

pidfile="/var/run/${name}.pid"
child_pidfile="/var/run/${name}.child.pid"

command="/usr/sbin/daemon"
command_args="-r -R 5 -P ${pidfile} -p ${child_pidfile} /usr/local/sbin/quark"

load_rc_config $name
run_rc_command "$1"
