#!/bin/sh

# PROVIDE: quark
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="quark"
rcvar="quark_enable"
desc="Quark Reverse Proxy"

command="/usr/sbin/daemon"
command_args="-r -P /var/run/${name}.pid -p /var/run/${name}.child.pid /usr/sbin/quark"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
